services:
  api:
    build:
      context: .
      dockerfile: src/RoomBuildingService.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=RoomDB;User Id=sa;Password=Admin@123;TrustServerCertificate=true;Encrypt=False
      - RabbitMQ__Host=rabbitmq
    depends_on:
      - sqlserver
      - rabbitmq

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin@123
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"   # Management UI